builders:
  vscode_extension_generator:
    import: "package:flutter_vscode/builder.dart"
    builder_factories: ["vscodeExtensionGenerator"]
    build_extensions:
      .dart:
        - ".vscode.g.dart"
    auto_apply: dependents
    build_to: source
  vscode_ts_generator:
    import: "package:flutter_vscode/builder.dart"
    builder_factories: ["vscodeTsGenerator"]
    build_extensions:
      ^lib/{{dir}}/{{file}}.dart:
        - "src/generated/api_controller.handlers.ts"
        - "src/generated/subscriptions.ts"
        - "src/generated/api_controller.ts"
    auto_apply: dependents
    build_to: source
