targets:
  $default:
    builders:
      flutter_vscode|vscode_dart:
        enabled: true
      flutter_vscode|vscode_ts:
        enabled: true
      flutter_vscode|vscode_extension:
        enabled: true
      flutter_vscode|vscode_package_json:
        enabled: true
      flutter_vscode|vscode_interop:
        enabled: true

builders:
  vscode_dart:
    import: "package:flutter_vscode/builder.dart"
    builder_factories: ["vscodeDartGenerator"]
    build_extensions: {".dart": [".vscode.g.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  vscode_ts:
    import: "package:flutter_vscode/builder.dart"
    builder_factories: ["vscodeTsGenerator"]
    build_extensions: {"lib/{{}}.dart": ["src/{{}}.handlers.ts"]}
    auto_apply: dependents
    build_to: source
    runs_before: ["source_gen|combining_builder"]
  vscode_extension:
    import: "package:flutter_vscode/builder.dart"
    builder_factories: ["vscodeExtensionGenerator"]
    build_extensions: {"lib/main.dart": ["src/extension.ts"]}
    auto_apply: dependents
    build_to: source
  vscode_package_json:
    import: "package:flutter_vscode/builder.dart"
    builder_factories: ["vscodePackageJsonGenerator"]
    build_extensions: {"lib/main.dart": ["package.json.updated"]}
    auto_apply: dependents
    build_to: source
  vscode_interop:
    import: "package:flutter_vscode/builder.dart"
    builder_factories: ["vscodeInteropGenerator"]
    build_extensions: {"lib/main.dart": ["lib/vscode_interop.dart"]}
    auto_apply: dependents
    build_to: source
