name: flutter_vscode
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  # Build dependencies needed for code generation
  analyzer: ^8.1.1
  build: ^3.0.0
  flutter:
    sdk: flutter
  # Add this for the annotations
  meta: ^1.9.1
  # Path package for file manipulation in tools
  path: ^1.8.3
  source_gen: ^3.1.0

dev_dependencies:
  # Add these for the build_runner
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

executables:
  generate_vscode_extension: generate_vscode_extension
