// This file is generated by the flutter_vscode package.
// Do not edit this file manually.

(function () {
  const vscode = acquireVsCodeApi();

  window.addEventListener('message', (event) => {
    const message = event.data;
    // Handle messages from the extension
  });

  function sendMessage(message) {
    vscode.postMessage(message);
  }

  // Make the sendMessage function available to the Flutter app
  window.sendMessage = sendMessage;
})();
